--À l'aide de sys@pdb_ecole

--Creation du profil pour Momo
CREATE PROFILE PROFIL_MOMO LIMIT
FAILED_LOGIN_ATTEMPTS 1
PASSWORD_LOCK_TIME 10/1440
SESSIONS_PER_USER 1
IDLE_TIME 3;

--Assignation du profil gestionnaire au usager correspondant
ALTER USER MOMO PROFILE PROFIL_MOMO;

--Creation du profil pour le gestionnaire
CREATE PROFILE PROFIL_GESTIONNAIRE LIMIT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 5/1440
SESSIONS_PER_USER 1
IDLE_TIME 3
PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION;

--Assignation du profil gestionnaire au usager correspondant
ALTER USER GESTIONNAIRE PROFILE PROFIL_GESTIONNAIRE;

--Creation du profil pour les registratiat
CREATE PROFILE PROFIL_REGISTRARIAT LIMIT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 3/1440
SESSIONS_PER_USER 2
IDLE_TIME 3
PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION;

--Assignation du profil registrariat aux usagers correspondant
ALTER USER REGISTRARIAT1 PROFILE PROFIL_REGISTRARIAT;

ALTER USER REGISTRARIAT2 PROFILE PROFIL_REGISTRARIAT;

--Creation du profil pour l'API
CREATE PROFILE PROFIL_API LIMIT
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 2/1440
SESSIONS_PER_USER 5
IDLE_TIME 3
PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION;

--Assignation du profil API au usager correspondant
ALTER USER API PROFILE PROFIL_API;

--Creation du profil pour l'enseignant
CREATE PROFILE PROFIL_ENSEIGNANT LIMIT
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1/1440
SESSIONS_PER_USER 10
IDLE_TIME 10
PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION;

--Assignation du profil enseignant au usager correspondant
ALTER USER API PROFILE PROFIL_ENSEIGNANT;