-- Création du role pour le gestionnaire
-- À l'aide de l'utilisateur sys@pdb_ecole:
CREATE ROLE GESTION;

GRANT CREATE SESSION TO GESTIONNAIRE;

GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO GESTION WITH ADMIN OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUATION TO GESTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON ETUDIANT TO GESTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON COURS TO GESTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON GROUPE TO GESTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON SEMESTRE TO GESTION;

-- Appliquer le role gestion pour l'utilisateur gestionnaire
GRANT GESTION TO GESTIONNAIRE
 -- Création du role registrariat
 -- À l'aide de l'utilisateur sys@pdb_ecole:
CREATE ROLE REGISTRATIAT_ROLE;

GRANT CREATE SESSION TO REGISTRATIAT_ROLE;

GRANT SELECT ON EVALUATION TO REGISTRATIAT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ETUDIANT TO REGISTRATIAT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON COURS TO REGISTRATIAT_ROLE;

GRANT SELECT ON GROUPE TO REGISTRATIAT_ROLE;

GRANT SELECT ON SEMESTRE TO REGISTRATIAT_ROLE;

-- Appliquer le role du registrariat aux deux registrariats
GRANT REGISTRATIAT_ROLE TO REGISTRARIAT1;

GRANT REGISTRATIAT_ROLE TO REGISTRARIAT2;

-- Création du role enseignement
-- À l'aide de l'utilisateur sys@pdb_ecole
CREATE ROLE ENSEIGNEMENT;

GRANT CREATE SESSION TO ENSEIGNEMENT;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUATION TO ENSEIGNEMENT;

GRANT SELECT ON GROUPE TO ENSEIGNEMENT;

GRANT SELECT ON SEMESTRE TO ENSEIGNEMENT;

GRANT SELECT ON ETUDIANT TO ENSEIGNEMENT;

GRANT SELECT ON COURS TO ENSEIGNEMENT;

-- Appliquer le role d'enseignement sur l'utilisateur enseignant.
GRANT ENSEIGNEMENT TO ENSEIGNANT;

-- Création du role api
-- À l'aide de l'utilisateur sys@pdb_ecole
CREATE ROLE API_ROLE;

GRANT CREATE SESSION TO API_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON GROUPE TO API_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON SEMESTRE TO API_ROLE;

GRANT SELECT ON ETUDIANT TO API_ROLE;

GRANT SELECT ON COURS TO API_ROLE;

GRANT SELECT ON EVALUATION TO API_ROLE;

-- Appliquer le role de l'api sur l'utilisateur api
GRANT API_ROLE TO API;